# Generated by Django 3.0.2 on 2021-11-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetLED',
            fields=[
                ('device_id', models.TextField(max_length=12, primary_key=True, serialize=False)),
                ('light_1', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('light_2', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('light_3', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('light_4', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
            ],
        ),
    ]
